### ISSUE TITLE
Supporting additional targets

### ISSUE THREAD

**Issue by fmckeogh** [GaloisInc/ivory-tower-stm32#11]
Hello,

I am interested in adding support for more targets, mainly STM32F411 and STM32F101 chips. I've read over the existing BSPs and have a few questions. To support a new target, do I only have to create a new folder containing .hs files for the various peripherals? Are there any pointers for getting started?

As an aside, would it be feasible to support AVR targets?

Thanks!

**Comment by acfoltzer** [comment]
Hi @chocol4te,

You'll also need to make some additions in central locations, starting with the [processor type](https://github.com/GaloisInc/ivory-tower-stm32/blob/ac012dae7db8f5f07648a600a6fa31c1785fdc3a/ivory-bsp-stm32/src/Ivory/BSP/STM32/Processor.hs#L13). Once you add the new variants to this type, you should be able to follow compiler warnings for incomplete patterns to see where else you'll need to dispatch to the correct implementations for your platform. Sorry there's not more explicit documentation for this process :frowning_face: 

AVR would certainly be feasible, but would require quite a bit more work than adding another STM32 variant. Since Ivory just generates C code, it can work for any platform with a C compiler.

**Comment by fmckeogh** [comment]
Thank you very much!

**Comment by acfoltzer** [comment]
@chocol4te you're quite welcome! I'm going to close out this issue for now, but feel free to get in touch if other issues arise.
